[package]
name = "day3"
version = "0.1.0"
authors = ["cortl <cortlan.bainbridge@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array_tool="1.0.3"